export const FirearmsCIA = [
  'PM63 CIA',
  'PM63 Fergie',
  'Mini Uzi CIA',
  'MP5K CIA BOps',
  'MP5K Sup CIA BOps',
  'MP5KPDW CIA BOps',
  'MP5KPDW Sup CIA BOps',
  'MP5A CIA BOps',
  'MP5A Sup CIA BOps',
  'MP5SD CIA Bops',
  'MP7 CIA BOps',
  'MP7Sup CIA BOps',
  'AKS 74U CIA BOps',
  'AKS 74USup CIA BOps',
  'Rattler CIA BOps',
  'RattlerSup CIA BOps',
  'MK 18 CIA BOps',
  'MK 18Sup CIA BOps',
  'AK 105 Alpha CIA BOps',
  'AK 105 Alpha Sup CIA BOps',
  'Type 56 CIA BOps',
  'MK17CQC CIA BOps',
  'MK17CQC Sup CIA BOps',
  'M4 CIA Undercover',
  'M4 CIA BOps',
  'M4 Sup CIA BOps',
  'MK17STD CIA BOps',
  'MK17STD Sup CIA BOps',
  'M249SPW CIA BOps',
  'M249SPW Sup CIA BOps',
  'LAMG CIA BOps',
  'LAMG Sup CIA BOps',
  'MK48 CIA BOps',
  'MK48 Sup CIA BOps',
  'PKP CIA BOps',
  'SVD CIA BOps',
  'VSS CIA BOps',
  'M110A1 CIA BOps',
  'M110A1Sup CIA BOps',
  'Sawnoff CIA',
];

export const FirearmsEnemy = [
  'Type 56',
  'AKM Blackhead',
  'AKM Insurgent',
  'Type 56 FAdvisor',
  'Type 56 Dot',
  'Type 56 Noob',
  'Type 56 UltraNoob',
  'PM63',
  'PM63 Noob',
  'Mini Uzi',
  'Mini Uzi Folded',
  'APC9K Sup FAdvsior',
  'AKS 74U',
  'AKS 74U Security',
  'AKS 74U Emir',
  'FAL Rifle',
  'SVD63',
  'VSS Vintorez',
  'RPK 74 LMG',
  'RPK LMG',
  'RPK16 Short LMG',
  'RP46_MG',
  'SR3_M',
  'Alpha AK',
  'TT 33 Pistol',
  'RPG 7',
  'RPG 26',
  'AT4 PICKED',
  'Hunting Shotgun',
  'SMLEMK3',
  'MP40',
  'M16 WM',
  'M16LR WM',
  'M14 WM',
  'M249 WM',
  'M240 WM',
  'MK17 WM',
  'MK17/GL WM',
  'MP5K WM',
  'MK14 GL WM',
  'AUG SSI Sup',
  'AUG LR SSI Sup',
  'P90 SSI',
  'P90 SSI Sup',
  'FS57 SSI',
  'FS57 SSI Sup',
  'SVU SSI',
  'M18 Pistol Security',
  'MP7 Holo',
  'Bren 2 Short FA Storm',
];

export const FirearmsNWS = [
  'Mini Uzi NWS',
  'Mini Uzi Pistol NWS',
  'AKM GL NWS',
  'M4/M203 NWS',
  'M4/M203 NWSSup',
  'AR M14 NWS',
  'AKM NWS',
  'AKM NWS Militia',
  'Type 56 NWS Militia',
  'Type 56 NWS',
  'M16A4 NWS',
  'M16A4 NWS Militia',
  'M4 NWS',
  'M4 Sup NWS',
  'Vulcan NWS',
  'Vulcan Sup NWS',
  'APC9K NWS',
  'APC9K Sup NWS',
  'M500PP NWS',
  'FAL NWS',
  'RPK NWS',
  'RPK NWS Militia',
  'M249 NWS',
  'SVD NWS',
  'SVU NWS',
];

export const FirearmsPistols = [
  'M9 Pistol',
  'M9Sup Pistol',
  'M17 Pistol',
  'M18 Pistol',
  'G19X Pistol',
  'G2240 Pistol',
  '1911 Pistol',
  'MPS45Sup Pistol',
  'TSS4 Pistol',
  'PPK Pistol CIA',
  'PPK Sup Pistol CIA',
  'G19 Pistol CIA BOps',
  'G19Sup Pistol CIA BOps',
  'G19X Pistol CIA BOps',
  'G19Custom Pistol CIA BOps',
  'G17 Pistol CIA BOps',
  'G2240 Pistol CIA BOps',
  'M18 Pistol CIA BOps',
  'M17 Pistol CIA BOps',
  'M9 Pistol CIA BOps',
  'HK45CT CIA UCov',
  'HK45CTSup CIA UCov',
  'HK45CT CIA BOps',
  'HK45CTSup CIA BOps',
  '1911 Pistol CIA BOps',
  'M9 Pistol NWS',
  'M9Sup Pistol NWS',
  'G17 Pistol NWS',
  'HS45 Pistol NWS',
  'HS45 Pistol Asset',
  'M9 Pistol NWS Militia',
  'G17 Pistol NWS Militia',
];

export const FirearmsRifles = [
  'M500PP',
  'M1014',
  'MP5A',
  'MP5SD',
  'M16A4',
  'M4 Carbine',
  'M4Sup',
  'MK 18',
  'MK 18Sup',
  'M4 URGI',
  'M4 URGISup',
  'M4/M203',
  'M4/M203Sup',
  'MK18/M203',
  'MK18/M203Sup',
  'M16A4/M203',
  'M249SPW',
  'M249Sup',
  'LAMG',
  'LAMG Sup',
  'M240L',
  'MK48',
  'MK48Sup',
  'MG338',
  'MG338Sup',
  'M16A4Marksman',
  'MK17LB',
  'MK17LB Sup',
  'M14EBR',
  'MK20SSR',
  'MK20SSRSup',
  'M110A1',
  'M110A1Sup',
  'MK17STD',
  'MK17STD Sup',
  'MK17CQC',
  'MK17CQC Sup',
  'MK17CQC EGLM',
  'MK17CQC EGLM Sup',
  'MK17STD EGLM',
  'MK17STD EGLM Sup',
  'Breacher Shotgun',
  'SniperRifle',
];

export const FirearmsSpecial = [
  'M4 ACOG Tango',
  'Mini Uzi SUP Tango',
  'Alpha AK Spectre Sup Tango',
  'Cruiser Shotgun',
];

// export FirearmsCIA + firearmsCIA
// export default {FirearmsCIA FirearmsEnemy};
