const Scopes = [
  'IronSights',
  'IronSightsAK',
  'IronSightsAKAlpha',
  'IronSights_Pistol',
  'IronSights_ConcealedSMG',
  'IronSights_Pistol1911',
  'IronSights_PistolM17',
  'IronSights_PistolCustomizable',
  'IronSights_PistolCustomizableMk27',
  'IronSightsSawedOff',
  'RedDot_Pistol',
  'RedDot_PistolMk27',
  'RedDot_PistolM17',
  'Holosight',
  'Holosight Black',
  'M68CCO',
  'RedDotT2',
  'M150RCO',
  'SpecterDR',
  'LPVO_6X',
  'LPVO_8X',
  'MGO240',
  'LROMK6_3_18X',
  'LROMK4_3_10X',
  'LROPM_5_25X',
  'MGOM145',
  'PK AS',
  'Kobra',
  'PK AV',
  'PO 35',
  'PSO1',
  'PSO1M2',
  'NSPUM2',
  'PSO39',
  'AUG 1.5X',
  'AUG 3X',
  'DarknessPenalty',
];

export default Scopes;
