const XPGainTable = [
  { label: 'missionFailed', value: '50' },
  { label: 'mission1Star', value: '300' },
  { label: 'mission2Star', value: '500' },
  { label: 'mission3Star', value: '600' },
  { label: 'bulletsFired', value: '0' },
  { label: 'bulletsHit', value: '0' },
  { label: 'kills', value: '100' },
  { label: 'killsStunnedTarget', value: '40' },
  { label: 'killsUnawareTarget', value: '40' },
  { label: 'hitsTaken', value: '0' },
  { label: 'doorsKicked', value: '0' },
  { label: 'doorForcedBreaches', value: '50' },
  { label: 'doorLockpicks', value: '50' },
  { label: 'doorsBlownUp', value: '80' },
  { label: 'explosivesUsed', value: '30' },
  { label: 'distanceWalkedMeters', value: '0' },
  { label: 'arrests', value: '250' },
  { label: 'rescues', value: '250' },
  { label: 'challengesCompleted', value: '500' },
  { label: 'bombsDisarmed', value: '80' },
  { label: 'wallsBreached', value: '100' },
  { label: 'completedHealthy', value: '100' },
  { label: 'perfectAccuracy', value: '200' },
  { label: 'warcrime', value: '-1000' },
  { label: 'sabotage', value: '50' },
];

export default XPGainTable;
